INFO 2025-08-04 02:16:24,776 autoreload 31612 36256 Watching for file changes with StatReloader
INFO 2025-08-04 02:16:41,039 autoreload 32288 20484 Watching for file changes with StatReloader
INFO 2025-08-04 02:19:11,426 autoreload 32288 20484 C:\Users\Kevin\PycharmProjects\MomsWebsite\clinical_scheduler\config\settings\development.py changed, reloading.
INFO 2025-08-04 02:19:12,005 autoreload 36200 32180 Watching for file changes with StatReloader
INFO 2025-08-04 02:19:19,136 autoreload 18392 34476 Watching for file changes with StatReloader
INFO 2025-08-04 02:22:34,790 autoreload 36648 38088 Watching for file changes with StatReloader
INFO 2025-08-04 02:25:54,403 autoreload 36692 18472 Watching for file changes with StatReloader
INFO 2025-08-11 17:52:23,210 autoreload 12712 23008 Watching for file changes with StatReloader
INFO 2025-08-11 18:00:37,094 autoreload 23892 25868 Watching for file changes with StatReloader
INFO 2025-08-11 18:03:49,275 autoreload 14388 22532 Watching for file changes with StatReloader
INFO 2025-08-11 18:07:27,364 autoreload 26468 27108 Watching for file changes with StatReloader
INFO 2025-08-11 18:07:53,724 autoreload 21016 21824 Watching for file changes with StatReloader
INFO 2025-08-11 18:10:45,942 autoreload 12452 27552 Watching for file changes with StatReloader
INFO 2025-08-11 18:11:56,307 autoreload 12240 26540 Watching for file changes with StatReloader
INFO 2025-08-11 18:12:38,940 autoreload 20168 24568 Watching for file changes with StatReloader
INFO 2025-08-11 18:12:52,670 autoreload 21824 24248 Watching for file changes with StatReloader
INFO 2025-08-11 18:13:04,063 autoreload 24696 24784 Watching for file changes with StatReloader
ERROR 2025-08-11 18:13:25,191 log 24696 19620 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-08-11 18:13:25,194 basehttp 24696 19620 "GET / HTTP/1.1" 400 143
ERROR 2025-08-11 18:13:25,232 log 24696 25892 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-08-11 18:13:25,233 basehttp 24696 25892 "GET /favicon.ico HTTP/1.1" 400 143
INFO 2025-08-11 18:17:13,568 autoreload 24696 24784 C:\Users\Kevin\PycharmProjects\MomsWebsite\clinical_scheduler\config\settings\development.py changed, reloading.
INFO 2025-08-11 18:17:14,248 autoreload 24032 9544 Watching for file changes with StatReloader
INFO 2025-08-11 18:17:17,709 autoreload 1748 23760 Watching for file changes with StatReloader
ERROR 2025-08-11 18:17:20,488 log 1748 25928 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\http\request.py", line 192, in get_host
    if domain and validate_host(domain, allowed_hosts):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\http\request.py", line 832, in validate_host
    return any(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\http\request.py", line 833, in <genexpr>
    pattern == "*" or is_same_domain(host, pattern) for pattern in allowed_hosts
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\utils\http.py", line 235, in is_same_domain
    pattern = pattern.lower()
AttributeError: 'tuple' object has no attribute 'lower'
ERROR 2025-08-11 18:17:20,490 basehttp 1748 25928 "GET / HTTP/1.1" 500 145
INFO 2025-08-11 18:18:40,061 autoreload 13220 4760 Watching for file changes with StatReloader
WARNING 2025-08-11 18:18:45,114 log 13220 27572 Not Found: /
WARNING 2025-08-11 18:18:45,114 basehttp 13220 27572 "GET / HTTP/1.1" 404 179
INFO 2025-08-17 12:40:04,060 autoreload 19844 2824 Watching for file changes with StatReloader
ERROR 2025-08-17 12:40:12,098 log 19844 19708 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-08-17 12:40:12,101 basehttp 19844 19708 "GET / HTTP/1.1" 400 143
ERROR 2025-08-17 12:40:12,131 log 19844 6912 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-08-17 12:40:12,132 basehttp 19844 6912 "GET /favicon.ico HTTP/1.1" 400 143
ERROR 2025-08-17 12:41:34,114 log 19844 18740 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-08-17 12:41:34,115 basehttp 19844 18740 "GET / HTTP/1.1" 400 143
INFO 2025-08-17 12:42:30,012 autoreload 7172 7124 Watching for file changes with StatReloader
INFO 2025-08-17 12:42:32,217 basehttp 7172 3904 "GET / HTTP/1.1" 200 4733
INFO 2025-08-17 12:42:32,231 basehttp 7172 3904 "GET /static/therapy/css/styles.css HTTP/1.1" 200 9717
INFO 2025-08-17 12:42:32,232 basehttp 7172 18280 "GET /static/therapy/js/main.js HTTP/1.1" 200 1732
ERROR 2025-08-17 12:42:48,544 log 7172 3904 Internal Server Error: /faq/
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py", line 22, in faq
    return render(request, 'therapy/faq.html', context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^

ERROR 2025-08-17 12:42:48,555 basehttp 7172 3904 "GET /faq/ HTTP/1.1" 500 145
INFO 2025-08-17 12:46:32,459 autoreload 7172 7124 C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py changed, reloading.
INFO 2025-08-17 12:46:33,202 autoreload 12976 16848 Watching for file changes with StatReloader
INFO 2025-08-17 12:48:43,738 autoreload 12976 16848 C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py changed, reloading.
INFO 2025-08-17 12:48:44,473 autoreload 19676 3904 Watching for file changes with StatReloader
INFO 2025-08-17 12:48:45,587 basehttp 19676 12432 "GET /scheduling/ HTTP/1.1" 200 3290
INFO 2025-08-17 12:48:45,598 basehttp 19676 12432 "GET /static/therapy/css/styles.css HTTP/1.1" 304 0
INFO 2025-08-17 12:48:45,599 basehttp 19676 10140 "GET /static/therapy/js/main.js HTTP/1.1" 304 0
ERROR 2025-08-17 12:48:46,280 log 19676 12432 Internal Server Error: /faq/
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py", line 22, in faq
    return render(request, 'therapy/faq.html', context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^

ERROR 2025-08-17 12:48:46,288 basehttp 19676 12432 "GET /faq/ HTTP/1.1" 500 145
INFO 2025-08-17 12:48:47,437 basehttp 19676 12432 "GET / HTTP/1.1" 200 4733
INFO 2025-08-17 12:48:48,397 basehttp 19676 12432 "GET /scheduling/ HTTP/1.1" 200 3290
INFO 2025-08-17 12:48:50,596 basehttp 19676 12432 "GET / HTTP/1.1" 200 4733
ERROR 2025-08-17 12:48:51,052 log 19676 12432 Internal Server Error: /faq/
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py", line 22, in faq
    return render(request, 'therapy/faq.html', context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^

ERROR 2025-08-17 12:48:51,059 basehttp 19676 12432 "GET /faq/ HTTP/1.1" 500 145
INFO 2025-08-17 12:51:30,242 autoreload 19676 3904 C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py changed, reloading.
INFO 2025-08-17 12:51:30,938 autoreload 8584 7612 Watching for file changes with StatReloader
INFO 2025-08-17 12:54:26,747 autoreload 19096 13136 Watching for file changes with StatReloader
INFO 2025-08-17 12:54:28,026 basehttp 19096 19216 "GET / HTTP/1.1" 200 4733
INFO 2025-08-17 12:54:28,040 basehttp 19096 19216 "GET /static/therapy/css/styles.css HTTP/1.1" 200 9717
INFO 2025-08-17 12:54:28,041 basehttp 19096 19216 "GET /static/therapy/js/main.js HTTP/1.1" 304 0
WARNING 2025-08-17 12:54:28,068 log 19096 19216 Not Found: /favicon.ico
INFO 2025-08-17 12:54:28,069 basehttp 19096 19216 - Broken pipe from ('127.0.0.1', 52026)
ERROR 2025-08-17 12:54:29,472 log 19096 2176 Internal Server Error: /faq/
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py", line 22, in faq
    return render(request, 'therapy/faq.html', context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^

ERROR 2025-08-17 12:54:29,481 basehttp 19096 2176 "GET /faq/ HTTP/1.1" 500 145
INFO 2025-08-17 12:55:53,951 autoreload 12640 3668 Watching for file changes with StatReloader
ERROR 2025-08-17 12:55:55,665 log 12640 18000 Internal Server Error: /faq/
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py", line 22, in faq
    return render(request, 'therapy/faq.html', context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^

ERROR 2025-08-17 12:55:55,674 basehttp 12640 18000 "GET /faq/ HTTP/1.1" 500 145
INFO 2025-08-17 12:56:10,834 basehttp 12640 18000 "GET / HTTP/1.1" 200 4733
INFO 2025-08-17 12:56:10,849 basehttp 12640 18000 "GET /static/therapy/css/styles.css HTTP/1.1" 304 0
INFO 2025-08-17 12:56:10,850 basehttp 12640 18000 "GET /static/therapy/js/main.js HTTP/1.1" 304 0
INFO 2025-08-17 12:56:28,084 basehttp 12640 18000 "GET /scheduling/ HTTP/1.1" 200 3290
ERROR 2025-08-17 12:58:03,881 log 12640 18000 Internal Server Error: /faq/
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py", line 22, in faq
    return render(request, 'therapy/faq.html', context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^

ERROR 2025-08-17 12:58:03,884 basehttp 12640 18000 "GET /faq/ HTTP/1.1" 500 145
ERROR 2025-08-17 13:07:20,688 log 12640 18504 Internal Server Error: /faq/
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py", line 22, in faq
    return render(request, 'therapy/faq.html', context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^

ERROR 2025-08-17 13:07:20,694 basehttp 12640 18504 "GET /faq/ HTTP/1.1" 500 145
WARNING 2025-08-17 13:07:20,712 log 12640 18504 Not Found: /favicon.ico
INFO 2025-08-17 13:07:20,712 basehttp 12640 18504 - Broken pipe from ('127.0.0.1', 52076)
INFO 2025-08-17 13:07:41,356 autoreload 17516 1964 Watching for file changes with StatReloader
INFO 2025-08-17 13:07:47,705 basehttp 17516 19180 "GET / HTTP/1.1" 200 4733
INFO 2025-08-17 13:07:47,721 basehttp 17516 19180 "GET /static/therapy/js/main.js HTTP/1.1" 304 0
INFO 2025-08-17 13:07:47,722 basehttp 17516 15308 "GET /static/therapy/css/styles.css HTTP/1.1" 200 9717
ERROR 2025-08-17 13:07:51,941 log 17516 15308 Internal Server Error: /faq/
Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\therapy\views.py", line 22, in faq
    return render(request, 'therapy/faq.html', context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kevin\PycharmProjects\MomsWebsite\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "therapy_faq" does not exist
LINE 1: ...rapy_faq"."order", "therapy_faq"."is_active" FROM "therapy_f...
                                                             ^

ERROR 2025-08-17 13:07:51,948 basehttp 17516 15308 "GET /faq/ HTTP/1.1" 500 145
INFO 2025-08-20 20:18:15,030 autoreload 10368 15560 Watching for file changes with StatReloader
